travis:
  secure:
    BINSTAR_TOKEN: pHmoKtybbpglDjARK9oXpfpvRPQUjEfkuNECLfqV3Lv6m9Rd1DuJwZ8T2xQVZycwxyRN4kdh7nQPCW033MM7vkFSqGvuhb92NgIQII7PmEGOuA23wh45FmJhdbJzh/3wGsm45ivOK5lDuYIDIOnFofcGaI9bYgWc8b1MC/CTq0zlpe0QUWjx6mKUpYL6+AY/0R7yUFUGKUpvjiTC46HTc+Dk42r7c85KpGoKcDyBOmfB38Bo/LGYaKqTIjBf6q8NbDDAXOjptuG4ds9CQ3FKgjJIhtRLt50mYb1j6Rmi97Rf1MRvCJEKAJgYKrdknW+6R+imzhq/entg6VIeIhxCv3UmArivk0k4HmBgg++Ss7Q5SugooZfsbgPAy8K79oaGuVZsw+KiEivpdw92Fp3IqQY35PviNk6mSsmw5dIYvLTRRPEF3CWY/EysgBsdkk91bSV93P5IXyypiZABeBpNHajm1UbeCtlGLIj37taVimNJgI23ZUok0qOGcdnNHA9KSE+IB2T40T47TsefUJMUadtFUomserEPB/vFMdmbWUAYF6b4c7RKKvGdRnMi/tuPQuj6NHw8UkaiheVquKDSbJCu6+11bnKZf7mOO0OXdLJ9khmSENwkasrO5aUIeE7nvywX5Gq7XqihBtW/nOfxw5nPBATGVdtFTRHDDQ2MGec=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
